name: scrap_car

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
    
jobs:
  hashtag-scrape:
    runs-on: macOS-latest
    env:
      ATLAS_URL: ${{ secrets.ATLAS_URL }}
      ATLAS_COLLECTION: ${{ secrets.ATLAS_COLLECTION }}
      ATLAS_DB: ${{ secrets.ATLAS_DB }}
    steps:
    - name: Start time
      run: echo "$(date) ** $(TZ=Asia/Jakarta date)"
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2   
    - name: Install packages
      run: |
        install.packages("devtools",dependencies = TRUE)
        install.packages("rvest", dependencies = TRUE)
        install.packages("tidyverse", dependencies = TRUE)
        install.packages("mongolite",dependencies = TRUE)
        devtools::install_github("r-lib/conflicted")

        
      shell: Rscript {0} 
    - name: Scrape Data Mobil
      run: Rscript scrap_car.R
